; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
board_build.filesystem = littlefs
platform = espressif32
board = esp32dev
framework = arduino
board_build.data_dir = data
lib_deps = 
	esphome/AsyncTCP-esphome@^2.1.4
	esphome/ESPAsyncWebServer-esphome@^3.3.0
	links2004/WebSockets@^2.6.1